app_api/urls.py
from django.urls import path

import app_api.views.county as county
import app_api.views.state as state

from app_api.views.search import StateSuggestions, CountySuggestions
from app_api.views.chart import PercentileSeries, PointSeries


app_name = 'api'
urlpatterns = [
    # entities
    path('county/list/', county.ListAll.as_view()),
    path('state/list/', state.ListAll.as_view()),
    # search suggestions
    path('search/suggestions/state/<str:query>', StateSuggestions.as_view(), name='suggest_state'),
    path('search/suggestions/county/<str:query>', CountySuggestions.as_view(), name='suggest_county'),
    # async chart series
    path('chart/percentiles/<int:data_set_id>/', PercentileSeries.as_view(), name='chart_percentiles'),
    path('chart/points/<int:data_set_id>', PointSeries.as_view(), name='chart_points'),
]

hda_privileged/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from . import views


app_name = 'priv'
urlpatterns = [
    # home/dashboard
    path('home/<int:indicator>/',
         login_required(views.PrivDashboardView.as_view()),
         name='dashboardselected'),
    path('home/',
         login_required(views.PrivDashboardView.as_view()),
         name='dashboard1'),
    # creating new health indicators
    path('indicator/add/',
         login_required(views.HealthIndicatorCreate.as_view()),
         name='createIndicator'),
    # update an existing health indicator
    path('indicator/update/<int:post_pk>/',
         login_required(views.HealthIndicatorUpdate.as_view()),
         name='updateIndicator'),
    # delete an existing health indicator
    path('indicator/delete/<int:post_pk>/',
         login_required(views.HealthIndicatorDelete.as_view()),
         name='deleteIndicator'),
    # delete an existing dataset
    path('dataset/delete/<int:post_pk>/',
         login_required(views.DataSetDelete.as_view()),
         name='deleteDataset'),
    # upload page
    path('upload/',
         login_required(views.UploadNewDataView.as_view()),
         name='uploadData'),
    # login
    path('login/',
         LoginView.as_view(template_name='hda_privileged/login.html', ),
         name='login'),
    # logout
    path('logout/', views.logout_view, name='logout'),
    # user management: Kim Hawkins
    path('usermanagement',
         login_required(views.user_management.as_view()), name='user_mgmt'),
    path('user/create', login_required(views.CreateNewPrivUser), name='create_user'),
    path('user/password/reset/<int:user>',
         login_required(views.PasswordReset.as_view()), name='pswd_reset'),
    path('user/deactivate/<int:user>',
         login_required(views.DelPrivUser.as_view()), name='deactivate'),
]

hda_public/urls.py
from django.urls import path, register_converter
from hda_public.views import (
    HomeView,
    StateView,
    CountyView,
    HealthView,
    ChartView,
    SearchView,
    IndicatorOverviewCounty,
    IndicatorOverviewState,
    UnknownLocationView,
)

# only successful method of import for this new view
from hda_public.views.location_selection import HealthStatePathView
from hda_public.converters import StateUSPSConverter, FIPS3Converter

# custom path converters to validate:
# - USPS 2-letter state codes:
register_converter(StateUSPSConverter, 'usps')
# - 3-digit FIPS codes.
register_converter(FIPS3Converter, 'fips3')

# we could acheive a prettier URL by slugifying the county names!
# https://stackoverflow.com/a/837835

urlpatterns = [
    # the home page:
    path('', HomeView.as_view(), name='home'),
    # a chart page that can show any counties given as a query parameter:
    path('chart/<int:data_set>', ChartView.as_view(), name='chart'),
    # location selection pages
    path('select/', StateView.as_view(), name='state_list'),
    path('select/<usps:short>', CountyView.as_view(), name='county_list'),
    # search results page
    path('search/', SearchView.as_view(), name='search'),
    # overview pages for states and counties
    path('state/<usps:state>', IndicatorOverviewState.as_view(), name='state'),
    path('county/<usps:state>/<fips3:county>', IndicatorOverviewCounty.as_view(), name='county'),
    path('unknown_location', UnknownLocationView.as_view(), name='unknown_location'),
]

hda_public/models.py
from django.db import models

# Create your models here.

app_api/views/chart.py
import json

from app_api.views.get_json import GetJSON
from hda_privileged.models import Data_Set, US_County, US_State


class PercentileSeries(GetJSON):

    def get_data(self, data_set_id):
        # THROWS
        data_set = Data_Set.objects.get(pk=data_set_id)
        percentiles = data_set.percentiles.all().order_by('rank')
        spline_points = [(round(p.rank * 100, 2), p.value) for p in percentiles]
        config = {
            'name': 'Percentiles',
            'type': 'spline',
            'color': 'gray',
            'enableMouseTracking': False,
            'marker': {
                'enabled': False,
            },
            'zIndex': -1,
            'data': spline_points,
        }
        return {'config': config}

class PointSeries(GetJSON):

    def try_get_county(self, fips_code):
        try:
            return US_County.objects.get(fips5=fips_code)
        except US_County.DoesNotExist:
            return None

    def try_get_point(self, data_set, county):
        return data_set.data_points.filter(county=county).first()

    def get_requested_counties(self):
        requested_state = self.request.GET.get('state', None)
        if requested_state:
            state = US_State.objects.get(pk=requested_state.upper())  # THROWS
            return ([county for county in state.counties.all().iterator()], [])
        else:
            requested_fips = self.request.GET.get('county', None)

            if requested_fips is None:
                raise Exception('Endpoint must be called with a state or county query string')

            fips_list = requested_fips.split(',')
            query_results = [(fips, self.try_get_county(fips)) for fips in fips_list]
            matched = [county for (_, county) in query_results if county]
            unmatched = [fips for (fips, county) in query_results if not county]
            return (matched, unmatched)


    def get_requested_points(self, data_set, counties):
        query_results = [(county, self.try_get_point(data_set, county)) for county in counties]
        points = [point for (_, point) in query_results if point]
        unmatched = [county for (county, point) in query_results if not point]
        return (points, unmatched)

    def point_to_dict(self, point):
        return {
            'x': round(point.rank * 100, 2),
            'y': point.value,
            'name': point.county.name,
        }

    def get_data(self, data_set_id):

        data_set = Data_Set.objects.get(pk=data_set_id)  # THROWS

        (counties, unmatched_fips) = self.get_requested_counties()  # THROWS

        (points, unmatched_counties) = self.get_requested_points(data_set, counties)

        config = {
            'name': 'Values',
            'type': 'scatter',
            'color': 'darkred',
            'enableMouseTracking': True,
            'marker': {
                'radius': 3,
                'symbol': 'circle',
            },
            'tooltip': {
                'pointFormat': r'{point.name}<br/>p: <b>{point.x}%</b><br/>v: <b>{point.y}</b><br/>',
                'valueDecimals': 1,
            },
            'data': [self.point_to_dict(p) for p in points]
        }

        errors = dict()

        if len(unmatched_fips) > 0:
            errors['no_county'] = '; '.join(unmatched_fips)

        if len(unmatched_counties) > 0:
            errors['no_fips'] = '; '.join(
                [f"{county.name}, {county.state.short}" for county in unmatched_counties]
            )

        return {
            'config': config,
            'errors': errors,
        }

hda_public/views/chartview.py
# ChartView - Django View for a single large Highcharts plot containing a single data set
# and some number of counties. Capable of plotting arbitrary counties using a comma-separated
# list of 5-digit FIPS codes included in the URL query string (an HTTP GET parameter).
# ~ Matthew Seiler

from django.contrib import messages
from django.views.generic import TemplateView

from hda_privileged.models import US_State, US_County, Data_Set


class ChartView(TemplateView):
    """
    Works with URLs of the following shape:
    - a keyword path parameter called 'data_set', which is an integer Data_Set ID
    - one of two query strings to specify what counties to display:
       + `?state=<USPS>`, where <USPS> is a 2-letter USPS postal code for a state
       + `?county=<FIPS_LIST>`, where <FIPS_LIST> is comma-separated list of *5-digit* FIPs codes

    Examples:
    * /chart/3?state=TN
    * /chart/3?county=01002,01005,01007

    The view will retrieve the requested data set, if it exists. It will validate the requested
    counties - creating a list of FIPS codes for all the counties in the requested state, or
    filtering requested FIPS codes to ones which match a county in the database. It includes
    the data set ID and list of counties in the template context, but *does not* query or attach
    the contents of the data set! (We rely on client-side JavaScript to request the chart series
    for the data set.)

    Each stage of context processing is broken into a separate function. Each function takes in
    the context dictionary and additional state from the previous stage, augments the context
    object in some way, and returns the updated context, a flag indicating whether to halt
    processing, and any additional state the next stage will require. The stages are listed in
    order and executed in the `decorate_context` function.
    """

    template_name = 'hda_public/chart.html'


    def data_set_decorator(self, context):
        """
        Given a data_set_id keyword parameter passed to the view, retrieves that data set and adds
        information about it to the context. Attaches the data set ID, year, and associated indicator
        (the entire Health_Indicator object).

        Matches the signature required by the 'decorate_context' method, but requires the previous
        decorator to pass through a health indicator object.

        :param context: template context
        :type context: dict
        :return: augmented context and continue flag
        :rtype: (dict, bool)
        :raises:
        """
        data_set_id = self.kwargs.get('data_set', None)
        if data_set_id is None:
            raise TypeError("Chart view needs a data set ID, but was not given one!")

        try:
            data_set = Data_Set.objects.get(pk=data_set_id)
            context['data_set_id'] = data_set.id
            context['year'] = data_set.year
            context['indicator'] = data_set.indicator

            return (context, True)

        except Data_Set.DoesNotExist:
            msg = f"There is no data set matching ID {data_set_id}"
            context['error'] = msg
            messages.error(self.request, msg)

            return (context, False)

    def try_get_state(self, usps):
        """
        Attempt to query a specific US_State from the data model, returning None if it is missing

        :param usps: ID of the state to retrieve, a 2-letter USPS code
        :type usps: str
        :return: the US_State matching the given USPS code
        :rtype: US_State | None
        """
        try:
            return US_State.objects.get(short=usps.upper())
        except US_State.DoesNotExist:
            return None

    def try_get_county(self, full_fips):
        """
        Attempt to query a specific county from the data model, returning None if it is missing

        :param full_fips: a 5-digit FIPS code for a county or county-equivalent
        :type full_fips: str
        :return: the county matching the given FIPS code
        :rtype: US_County | None
        """
        try:
            return US_County.objects.get(fips5=full_fips)
        except US_County.DoesNotExist:
            return None

    def state_request_decorator(self, context):
        """
        Looks for an HTTP GET parameter named 'state', and uses it to add a list of county FIPS
        codes to the context. Does nothing to the context if the 'state' parameter is missing
        (including not halting processing - we want to let another function add counties instead).


        If the requested state exists, adds the full name of the state under the 'place_name' key,
        for use in the chart title; and a list of 5-digit FIPS codes to the 'counties' key
        including each county in the state. (This may include counties that are not in the data set!)

        If the requested state does not exist, adds an error message to the context and to the
        message framework, and returns a 'False' flag in the return tuple to stop future functions
        from executing.

        Matches the signature required by 'decorate_context'.

        :param context: template context dictionary
        :type context: dict
        :return: augmented context and flag
        :rtype: (dict, bool)
        """

        requested_state = self.request.GET.get('state', None)

        # Guard: if there is no state query string,
        # do nothing and let the next context processing step proceed
        if requested_state is None:
            return (context, True)

        state = self.try_get_state(requested_state)
        if state is None:
            # the state parameter might not match an actual state!
            msg = f"The USPS code '{requested_state}' doesn't match a US State"
            context['error'] = msg
            messages.error(self.request, msg)
            return (context, False)  # stops the pipeline
        else:
            context['place_name'] = state.full
            # current_state added to pass in url param when user chooses to go from
            # all counties chart to county selection page: Kim Hawkins
            context['current_state'] = state.short
            context['counties'] = [
                county.fips5 for county in state.counties.all().iterator()]
            return (context, True)

    def county_request_decorator(self, context):
        """
        Looks for an HTTP GET parameter named 'county', and uses this to add county FIPS codes
        to the context. Does nothing if the context already contains a non-empty list under the
        key 'counties'.

        The 'county' query string should be a comma-separated list of 5-digit FIPS codes. This
        function queries for each of these FIPS codes to determine if that county actual exists
        in the data model. FIPS codes which do not match a county object are concatenated into
        a string which is added to the context under the 'unknown_fips' key, and to the messages
        framework at the 'warning' level.

        If only a single county was requested, the context is further augmented with 'place_name'
        and 'parent_state' keys, which are used to make a prettier chart title and a button that
        links to a chart of all the counties in the same state.

        :param context: template context dictionary
        :type context: dict
        :return: tuple of augmented context and flag for decorate_context
        :rtype: (dict, bool)
        """

        # Guard: if another decorator already added counties, do nothing!
        # (We could change this to merge additional counties if we wanted?)
        if 'counties' in context and len(context['counties']) > 0:
            return (context, True)

        # No counties added yet: try to get the 'county' parameter from GET query string
        fips_str = self.request.GET.get('county', None)

        # Guard: there was no paramater specifying what counties to show!
        if fips_str is None:
            messages.warning(self.request, 'No counties were selected; this chart will only show the percentile distribution.')
            return (context, True)

        fips_list = fips_str.split(',')
        # list of pairs, (FIPs, County or None)
        query_results = [(fips, self.try_get_county(fips)) for fips in fips_list]
        # list of County
        counties = [county for (_, county) in query_results if county is not None]
        # list of FIPs that did not match a county
        missing = [fips for (fips, county) in query_results if county is None]

        # include context for invalid/unknown FIPS codes
        if len(missing) > 0:
            missing_str = ", ".join(missing)
            context['unknown_fips'] = missing_str
            msg = f"The following FIPS codes did not match a county: {missing_str}"
            messages.warning(self.request, msg)

        # if we are only showing a single county,
        # add some extra context to make the view prettier
        if len(counties) == 1:
            c = counties[0]
            context['place_name'] = f"{c.name}, {c.state.short}"
            context['parent_state'] = c.state.short

        context['counties'] = [c.fips5 for c in counties]
        return (context, True)

    def decorate_context(self, context):
        """
        A helper function that chains several other functions together, each of which takes in
        a context dictionary and returns the same dictionary after adding something to it.
        This forms a pipeline of functions that the context passes through before finally being
        returned, wherein a little more information is added to the context at each step.

        The helper functions for pipeline steps should have the following signature:

            (dict, *) -> (dict, bool, *)

        where the bool signifies whether the pipeline should be allowed to continue. (This allows

hda_public/templates/hda_public/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <style>
        img.a {
            vertical-align: middle;
        }
    </style>
    <!-- Meta stuff, from: https://getbootstrap.com/docs/3.3/getting-started/#template -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--
    Bootstrap's base CSS via CDN - previously we hosted this ourselves but
    I think I've been converted: https://stackoverflow.com/q/24132951
    NOTE that this is Bootstrap 3.3.x!
    -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- FontAwesome icon fonts -->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/solid.css"
          integrity="sha384-VGP9aw4WtGH/uPAOseYxZ+Vz/vaTb1ehm1bwx92Fm8dTrE+3boLfF1SpAtB1z7HW"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/fontawesome.css"
          integrity="sha384-1rquJLNOM3ijoueaaeS5m+McXPJCGdr5HcA03/VHXxcp2kX2sUrQDmFc3jR5i/C7"
          crossorigin="anonymous">

    <!-- Our CSS on top of Bootstrap -->
    <link href="{% static 'css/theme.css' %}" rel="stylesheet">

    <title> {% block title %}{% endblock %} </title>

</head>
<body>
<div class="container">
    <h1></h1>
    {% block nav %}
    <nav class="navbar navbar-default navBackground">
        <div class="container-fluid">
            <div class="navbar-header">
                <!-- brand image icon (ETSU shield) -->
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="/static/img/eshield.png"
                        alt="ETSU shield logo"
                        width="45"
                        height="45" />
                </a>
                <!-- brand texts -->
                <div class="navbar-brand-text navbar-left">
                    <h1>College of Public Health</h1>
                    <h2>Indicator Visualization Tool</h2>
                </div>
                <!-- menu button that shows when collapsed -->
                <button type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#menuDropdown"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- items that collapse on mobile -->
            <div class="collapse navbar-collapse" id="menuDropdown">

                <!-- search box -->
                <form class="navbar-form navbar-left" action={% url 'search' %} method="GET">
                    <div id='search_container' class="form-group">
                        <input id="search_box"
                            autocomplete="off"
                            name="query"
                            type="search"
                            class="form-control"
                            placeholder="Search counties..."/>
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>

                <!-- home button -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav navbar-nav navbar--right">
                        <a href="{% url 'home' %}"> <i class="fa fa-home"
                                        style="font-size:20px"></i> Home</a>

                    </li>
                </ul>
            </div>
        </div><!-- /container -->
    </nav><!-- /navbar-default -->
    {% endblock %}
</div><!-- /container -->

<div class="container">

    {% block content %}

    {% endblock %}
</div>

<hr>
{% block footer %}
    <footer class="application-footer">
        <div class="container" style="bottom:0">
            <a href="{% url 'priv:login' %}" style="float:right; color:MidnightBlue"><i class="fas fa-user"></i>
                Admin</a>
            <h4 style="float:left; font-size:10px">ETSU College of Public Health | 104 Lamb Hall | Box 70623 | Johnson
                City, TN 37614 | Tel.: 423-439-4243 | Fax.: 423-439-5238</h4>
        </div>
    </footer>
{% endblock %}

<!-- Bootstrap's JS (again, note that this is 3.3.x) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js'></script>

<!-- Place for child pages to add more Javascript if needed -->
{% block extra_scripts %}
{% endblock %}


<!-- autocomplete for search -->
<!-- this loads the library: typeahead.js + bloodhound.js -->
<script src="{% static 'js/typeahead.bundle.js' %}"></script>
<!-- this loads a function that sets up our instance of the library -->
<script src="{% static 'js/typeahead_config.js' %}"></script>
<!-- this executes that function. it requires some URLs that only the template generator knows
the canonical version of, so we construct them here and pass them in as strings -->
<script>
    const typeahead_cfg = {
        prefetch: {
            county: "{% static 'prefetch/county.json' %}",
            state: "{% static 'prefetch/state.json' %}"
        },
        remote: {
            county: "{% url 'api:suggest_county' '%Q%' %}",
            state: "{% url 'api:suggest_state' '%Q%' %}",
            wildcard: "{{ '%Q%' | urlencode }}",
        }
    };
    TypeaheadSetup.init(typeahead_cfg);
</script>
</body>
</html>

hda_public/templates/hda_public/chart.html
{% extends "hda_public/base.html" %}
{% comment %}
Template for the primary chart page: shows a single, large chart that plots the percentile curve
for a single data set, along with scatter plot points for a specific county or counties.

Context:
  Required:
    indicator (Health_Indicator)
      used for the name and ID of the health indicator being plotted
    year (int)
      displays the year the data set is from
    counties (List FIPS-5)
      list of 5-digit FIPS codes (str) of counties to include in plot

  Optional:
    data_set_id (int)
      ID of Data Set to plot
      (If this is missing, the page just shows a "woops, sorry" message)
    parent_state (USPS)
      If present, used to include a button that links to a plot of all counties in that state
    messages (List django.contrib.messages)
      Messages added by the messages framework
    place_name (string)
      Used to augment the chart title with a location name if a single county or state is being plotted

Spring 2019 - Jean-Marie Nshimiyimana, Matthew Seiler
{% endcomment %}


{# Need this to use the "static" template tag later in the file #}
{% load static %}

{# This lets us a use a custom tempate tag to encode URL query strings #}
{% load urlparams %}

{% block title %}{{indicator.name}} ({{year}}){% endblock %}

{% block content %}

{% comment %} Contains the chart if a data set ID was provied {% endcomment %}
<div class="row">
  {% if data_set_id %}
  <div id="chartdiv"></div>
    {% comment %}If user is viewing one county in a state button allows user to view all counties in state{% endcomment %}
    {% if parent_state %}
      <p>See all counties in this state: <a role="button"
            href="{% url 'chart' data_set_id %}{% urlparams state=parent_state %}"
            class="btn btn-default btn-sm">{{ indicator.name }}: {{parent_state}}</a></p>
    {% comment %}Else if user is viewing all counties in a state, give option to view one county: Kim Hawkins{% endcomment %}
    {% elif place_name %}
      <p>See a county in this state:
        <a role="button"
          href="{% url 'county_list' current_state %}{% urlparams choice='county' %}"
          class="btn btn-default btn-sm">{{ indicator.name }}: {{place_name}}</a>
      </p>
    {% endif %}

  {% else %}
  <p>Please select a state and health indicator to display data for</p>
  {% endif %}

</div>

{% comment %} Contains any alert/notification messages {% endcomment %}
<div class="row">
  <div class='form-group'>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <div
            class="alert alert-{{ message.level_tag }}"
            role="alert">
            {{ message }}
          </div>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>

{% endblock %}


{% block extra_scripts %}

{% comment %} Highchart script CDN  {% endcomment %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<!-- optional, but adds more features -->
<script src="http://code.highcharts.com/modules/offline-exporting.js"></script>
<script src="http://code.highcharts.com/modules/export-data.js"></script>

{% comment %} Our Highcharts configuration and loading code {% endcomment %}
<script src="{% static 'js/highcharts_tooltip_override.js' %}"></script>
<script src="{% static 'js/highcharts_single.js' %}"></script>

{% if data_set_id %}
<script>
(function(){
  /*{% comment %}
  Generate the URL we will request the percentile spline series from.
  {% endcomment %}*/
  const percentile_url = "{% url 'api:chart_percentiles' data_set_id %}";

  /*{% comment %}
  Generate the URL we will request the data point scatter series from.
  Converts the counties list into a single comma-separated string, then
  appends it to the base URL for the endpoint.
  {% endcomment %}*/
  const county_list = "{{ counties | join:',' }}";
  const point_url = "{% url 'api:chart_points' data_set_id %}?county=" + county_list;

  /*{% comment %}
  Generate the title for the chart
  {% endcomment %}*/
  const title = "{{indicator.name}} ({{year}})" {% if place_name %} + " {{place_name}}"{% endif %};

  SingleChart.large(
    'chartdiv',
    percentile_url,
    point_url,
    title
  );
}());
</script>
{% endif %}

{% endblock %}

hda_public/templates/hda_public/county_list.html
{% extends 'hda_public/base.html' %}
{% comment %}
Page that displayes paginated list of counties in a particular state to select from.
Links are to the county overview page.

Oluwafeyisayo Oyeniyi, Kim Hawkins, Matt Seiler
{% endcomment %}

{# This lets us a use a custom tempate tag to encode URL query strings #}
{% load urlparams %}

{% block title %} Counties {% endblock %}

{% block content %}

{# Link back to the state selection page #}
<a href="{% url 'state_list' %}"> &larr; View all states </a>

{# header shows the currently selected state #}
<h3>{{ state }}</h3>

{# Table of counties in this state for the current page #}
<table class="table table-hover">
	<thead>
		<tr>
            <th scope ="col">Fips Code</th>
		    <th scope="col">Name</th>
		</tr>
	</thead>
    <tbody>
    {% for county in counties %}
		<tr>
            <td>{{ county.fips }}</td>
            <td><a href="{% url 'county' state_short_name county.fips %}">{{ county.name }}</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{# Page numbering #}
<ul class="pagination center-align">

{% if page_obj.has_previous %}
    <li class="">
        <a href="{% url 'county_list' state_short_name %}{% urlparams page=page_obj.previous_page_number %}">Previous</a>
    </li>
{% endif %}

{% for i in range %}
    <li class="{% if page_obj.number == forloop.counter %}active{% endif %}">
        <a href="{% url 'county_list' state_short_name %}{% urlparams page=forloop.counter %}">{{ forloop.counter }}</a>
    </li>
{% endfor %}

{% if page_obj.has_next %}
    <li class="">
        <a href="{% url 'county_list' state_short_name %}{% urlparams page=page_obj.next_page_number %}">Next</a>
    </li>
{% endif %}
</ul>

{% endblock %}

hda_public/templates/hda_public/dashboard.html
{% extends 'hda_public/base.html' %}

{# This lets us a use a custom tempate tag to encode URL query strings #}
{% load urlparams %}

{% block title %} CPH Indicator Visualization Tool {% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Find a Location</h1>
    <p>
        This site provides visualization and ranking of national public health indicators for counties in the United States.
        Find your county and select an indicator to see how it compares to other counties in the nation!
    </p>
    <p>
        <a class="btn btn-primary btn-lg"
            href="{% url 'state_list' %}{% urlparams choice='county' %}"
            role="button"
            name="selected"
            value="county">Find a county</a>
        <a class="btn btn-primary btn-lg"
            href="{% url 'state_list' %}{% urlparams choice='state' %}"
            role="button"
            name="selected"
            value="state">Find a state</a>
    </p>
</div>

{% endblock %}

hda_public/templates/hda_public/unknown_location.html
{% extends 'hda_public/base.html' %}

{% load urlparams %}

{% block title %} Unknown location {% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>:(</h1>
    <p>We couldn't find the location you requested.</p>
    <p>
        <a href="{% url 'state_list' %}{% urlparams choice='county' %}"
            class="btn btn-default btn-lg"
            role="button">Look for a county</a>
        <a href="{% url 'state_list' %}{% urlparams choice='state' %}"
            class="btn btn-default btn-lg"
            role="button">Look for a state</a>
    </p>
</div>
{% endblock %}