app_api/urls.py
from django.urls import path

import app_api.views.county as county
import app_api.views.state as state

from app_api.views.search import StateSuggestions, CountySuggestions
from app_api.views.chart import PercentileSeries, PointSeries


app_name = 'api'
urlpatterns = [
    # entities
    path('county/list/', county.ListAll.as_view()),
    path('state/list/', state.ListAll.as_view()),
    # search suggestions
    path('search/suggestions/state/<str:query>', StateSuggestions.as_view(), name='suggest_state'),
    path('search/suggestions/county/<str:query>', CountySuggestions.as_view(), name='suggest_county'),
    # async chart series
    path('chart/percentiles/<int:data_set_id>/', PercentileSeries.as_view(), name='chart_percentiles'),
    path('chart/points/<int:data_set_id>', PointSeries.as_view(), name='chart_points'),
]

hda_privileged/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from . import views


app_name = 'priv'
urlpatterns = [
    # home/dashboard
    path('home/<int:indicator>/',
         login_required(views.PrivDashboardView.as_view()),
         name='dashboardselected'),
    path('home/',
         login_required(views.PrivDashboardView.as_view()),
         name='dashboard1'),
    # creating new health indicators
    path('indicator/add/',
         login_required(views.HealthIndicatorCreate.as_view()),
         name='createIndicator'),
    # update an existing health indicator
    path('indicator/update/<int:post_pk>/',
         login_required(views.HealthIndicatorUpdate.as_view()),
         name='updateIndicator'),
    # delete an existing health indicator
    path('indicator/delete/<int:post_pk>/',
         login_required(views.HealthIndicatorDelete.as_view()),
         name='deleteIndicator'),
    # delete an existing dataset
    path('dataset/delete/<int:post_pk>/',
         login_required(views.DataSetDelete.as_view()),
         name='deleteDataset'),
    # upload page
    path('upload/',
         login_required(views.UploadNewDataView.as_view()),
         name='uploadData'),
    # login
    path('login/',
         LoginView.as_view(template_name='hda_privileged/login.html', ),
         name='login'),
    # logout
    path('logout/', views.logout_view, name='logout'),
    # user management: Kim Hawkins
    path('usermanagement',
         login_required(views.user_management.as_view()), name='user_mgmt'),
    path('user/create', login_required(views.CreateNewPrivUser), name='create_user'),
    path('user/password/reset/<int:user>',
         login_required(views.PasswordReset.as_view()), name='pswd_reset'),
    path('user/deactivate/<int:user>',
         login_required(views.DelPrivUser.as_view()), name='deactivate'),
]

hda_privileged/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .models import Health_Indicator, Profile
from .upload_reading import UPLOAD_FORMAT_CHOICES, CHOICE_NAME


class HealthIndicatorForm(ModelForm):
    """
    health indicator form (for multichart view)
    """
    class Meta:
        """ """
        model = Health_Indicator
        fields = ['name', 'important']
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'e.g. \'Poor physical health days\'',
                    'size': 100,
                }
            )
        }


class LoginForm(forms.Form):
    """
    login form for user management

    """
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': "form-control", 'placeholder': "Username"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': "form-control", 'placeholder': "Password"}
        )
    )


# This form needed to get user first and last name and email for creating a new user
# Django default create user form only covers username and password
# Developed by Kim Hawkins
"""param:UserCreationForm: A Django ModelForm for creating a new user"""


class NewUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2',)

# This form ensures Profile model is included when creating a new user: Hawkins
# Choice of user type: administrator or assistant


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        # Field class assumes the value is required and will raise a Validation Error exception
        fields = ('utype',)
        # override label else it displays 'utype'
        labels = {'utype': _('User Type'), }


# Not using a ModelForm because this needs to include data for
# both Document and Data_Set model classes - we could make an
# additional Model class (e.g. NewDataUpload entity) with the
# right fields and then create a ModelForm from that, but that
# seems like an extra step.
class UploadNewDataForm(forms.Form):
    """
    Form subclass for displaying an upload form for new data sets.
    """
    file = forms.FileField(
        label='Data File',
        help_text='File containing data in CSV format'
    )

    column_format = forms.ChoiceField(
        label='CSV file format',
        help_text='What columns to use to identify counties in the uploaded CSV file',
        widget=forms.RadioSelect,
        choices=UPLOAD_FORMAT_CHOICES,
        required=True,
        initial=CHOICE_NAME
    )

    # This needs to be required once we have a way to create new ones #
    indicator = forms.ModelChoiceField(
        queryset=Health_Indicator.objects.all(),
        label='Health indicator',
        help_text='The health indicator/metric that this file contains data for',
        required=False
    )

    source = forms.CharField(
        label='Data source',
        help_text='The source/provenance of the data',
        required=False,
        widget=forms.Textarea(attrs={'rows': 3})
    )

    # The default value should not be hardcoded!
    year = forms.IntegerField(
        label='Data year',
        help_text='Year this data is from',
        initial=2018,
        min_value=1000,
        max_value=9999
    )

hda_privileged/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, get_user, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db import transaction
# Error message for user if trying to delete a foreign key
from django.db.models.deletion import ProtectedError
# wraps import for custom decorator
from functools import wraps
import json

from .forms import LoginForm, UploadNewDataForm, HealthIndicatorForm, NewUserForm, ProfileForm
from .models import Document, Data_Set, Data_Point, Percentile, Health_Indicator, Profile
from .percentile import get_percentiles_for_points, assign_percentiles_to_points
from .upload_reading import read_data_points_from_file


# ------------------------------------------------
# The user_log-in function will handle the log in
# functionality and redirect the loggedin user to
# desired page
# ------------------------------------------------
def user_login(request):
    """

    :param request: 

    """
    form = LoginForm()
    next = ""
    if request.GET:
        next = request.GET['next']
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # The 'sample' routing will be changed to the desired landing page
                    # that will be displayed after authenticated user logs in
                    # If there is no next page to rout to, the routing will go to the
                    # Default landing page
                    if next == "":
                        return redirect(reverse('priv:dashboard1'))
                    else:
                        # If there is a next page, the routing will automatical go to the
                        # next page after a user is authenticated
                        return redirect(next)
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    args = {'form': form, 'next': next}
    return render(request, 'hda_privileged/login.html', args)


def logout_view(request):
    """

    :param request: 

    """
    logout(request)
    return redirect('priv:login')


# custom decorator to check if user is admin for user management module: Hawkins
# tutorial followed: https://gist.github.com/canokay/7c76e38b1c403f24768583e49d22871c
# IMPORTANT!!!!
# If using this decorator on a class, it must be used within the class with a method
# that overrides the dispatcher for that class. See user_management class for example.


"""param:view_func: a python function that Django uses as an object
   returns: the python function as decorator for admin or superuser: or redirects to dashboard: returns a wrapped response"""


def admin_or_super_functiondecorator(view_func):
    def wrap(request, *args, **kwargs):
        # Get user then get user's profile
        p = request.user.profile.utype
        if p == 'AD' or request.user.is_superuser:
            return view_func(request, *args, **kwargs)
        # User is not admin or superuser but is assistant, redirect to dashboard
        else:
            return redirect('priv:dashboard1')

    return wrap


# User Management dashboard lists all users with links to reset a password, deactivate
# an account, or create a new user: Hawkins
"""param:TemplateView: Django generic class-based view
   returns: context: all user objects for display in template table"""


class user_management(TemplateView):
    template_name = 'hda_privileged/usr_mgmt.html'
    model = User
    fields = ('username', 'first_name', 'last_name')

    # https://docs.djangoproject.com/en/2.2/topics/class-based-views/intro/
    @method_decorator(admin_or_super_functiondecorator)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        :param **kwargs:
        """
        # call super to get the base context
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context


# Allows a specified user to create new user accounts.
# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
# Developed by Kim Hawkins


"""param:request: request objects pass state through the system
   returns: save user and redirect to login if POST request, else return create user form"""


# controls transactions explicitly
# If successful, changes are committed to db
# If exception, changes are rolled back
@transaction.atomic
@admin_or_super_functiondecorator
def CreateNewPrivUser(request):
    # If the user has clicked 'create user', get user data from form
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        # if user entries in both forms are valid
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user.is_active = True
            # extra steps to tie custom profile field to new user
            # varied from tutorial here because of integrity error with user_id
            for field in profile_form.changed_data:
                setattr(user.profile, field,
                        profile_form.cleaned_data.get(field))
            user.profile.save()
            return redirect('priv:dashboard1')
    # else the user has not clicked 'create user', return blank form
    else:
        users = User.objects.all().select_related('profile')
        current = request.user
        p = users.filter(username=current.username)
        form = NewUserForm()
        profile_form = ProfileForm()
    return render(request, 'hda_privileged/create_user.html', {'form': form, 'profile_form': profile_form})


# Allows administrator to deactivate an active user.
# Developed by Feyi


class DelPrivUser(TemplateView):
    """
    update the user's privileges
    :param UpdateView:
    :return:
    """
    # model = Profile
    template_name = 'hda_privileged/deactivate_user.html'

    # https://docs.djangoproject.com/en/2.2/topics/class-based-views/intro/
    @method_decorator(admin_or_super_functiondecorator)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, user):
        selected_user = User.objects.filter(id=user).first()
        return render(request, 'hda_privileged/deactivate_user.html', {'user': selected_user})

    def post(self, request, user):
        """

        :param request:
        :param user:
        :return:

        """
        selected_user = User.objects.filter(id=user).first()
        selected_user.is_active = False
        selected_user.save()
        messages.success(request, 'The user was successfully deactivated')
        return redirect('priv:user_mgmt')


"""
    param: Django's generic TemplateView
    returns: selected_user: user that was clicked on user management template and passed through url param
    render: password reset template, user object for selected user, and Django's SetPasswordForm
    redirect: password change successful, redirect to user management page
    """


class PasswordReset(TemplateView):
    template_name = 'hda_privileged/password_reset.html'

    # https://docs.djangoproject.com/en/2.2/topics/class-based-views/intro/
    @method_decorator(admin_or_super_functiondecorator)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    # get user selected on user management dashboard from user id in url params
    def get_selected_user(self):
        selected_id = self.kwargs.get('user', None)
        selected_user = User.objects.filter(user_id=selected_id).first()
        return selected_user

    # get the user object and pass to Django's set password form
    # SetPasswordForm was used because it does not involve email
    # and admin will not be required to enter old pw (user forgot their password)
    def get(self, request, user):
        selected_user = User.objects.filter(id=user).first()
        form = SetPasswordForm(selected_user)
        return render(request, 'hda_privileged/password_reset.html', {'usr': selected_user, 'form': form})

    # form is being submitted; validate form. If successful: save new password, success message for user,
    # redirect to user management dashboard. If not successful, give user an error message, render form again.
    def post(self, request, user):
        selected_user = User.objects.filter(id=user).first()
        form = SetPasswordForm(selected_user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'The password was successfully updated')
            return redirect('priv:user_mgmt')
        else:
            messages.error(request, 'Please correct the error below')
        return render(request, 'hda_privileged/password_reset.html', {'usr': selected_user, 'form': form})

    # to create a new health indicator


class HealthIndicatorCreate(CreateView):
    """
    creates new health indicator
    """
    template_name = 'hda_privileged/create_metric.html'
    model = Health_Indicator
    form_class = HealthIndicatorForm
    success_url = reverse_lazy('priv:dashboard1')

hda_privileged/templates/hda_privileged/base.html
{% load staticfiles %}
{%block header %}
<!DOCTYPE html>
<html>
<head>
  <!-- Meta stuff, from: https://getbootstrap.com/docs/3.3/getting-started/#template -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--
    Bootstrap's base CSS via CDN - previously we hosted this ourselves but
    I think I've been converted: https://stackoverflow.com/q/24132951
    NOTE that this is Bootstrap 3.3.x!
    -->
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
    crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- FontAwesome icon fonts -->
   <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.3.1/css/solid.css"
    integrity="sha384-VGP9aw4WtGH/uPAOseYxZ+Vz/vaTb1ehm1bwx92Fm8dTrE+3boLfF1SpAtB1z7HW"
    crossorigin="anonymous">
   <link rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.3.1/css/fontawesome.css"
    integrity="sha384-1rquJLNOM3ijoueaaeS5m+McXPJCGdr5HcA03/VHXxcp2kX2sUrQDmFc3jR5i/C7"
    crossorigin="anonymous">

    <!-- Our CSS on top of Bootstrap -->
   <link href="{% static 'css/theme.css'%}" rel="stylesheet">
</head>
{% endblock %}

<body>
<div class="container">

{% block nav %}
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    {% comment %} Navigation bar contents, left and right {% endcomment %}
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'priv:dashboard1' %}"><i class="fa fa-home" style="font-size:20px"></i></a></li>
        <li><a href="{% url 'priv:dashboard1' %}">Manage Data</a></li>
        <li><a href="{% url 'priv:user_mgmt' %}">Manage Users</a></li>
        <li><a href="{% url 'home' %}">Public Site</a></li>
        <li><a href="https://www.etsu.edu/cph/">CPH</a></li>
      </ul>
      <p class="navbar-text navbar-right">
        <i class="fa fa-user"></i>&nbsp;{{ request.user.username }}&nbsp;&bull;
        <a href="{% url 'priv:logout' %}" class="navbar-link">sign out</a>
      </p>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock %}

    {% block content %}
    {% endblock %}

</div>

	<hr>
	<footer class="application-footer">
		<div class="container" style="bottom:0">

		</div>
	</footer>
</body>
</html>

hda_privileged/templates/hda_privileged/labeled_form_group.html
<div class="form-group">
    <label
        for="{{ field.id_for_label }}"
        class="col-sm-2 control-label">{{ field.label }}</label>

    <div class="col-sm-10">
        {{ field }}
    </div>

    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>

hda_privileged/templates/hda_privileged/privdashboard.html
{% extends 'hda_privileged/base.html' %}
{% load staticfiles %}
{% block content %}

    <head>
        <!-- Make health indicator selected same color as navbar -->
        <style>.nav-pills > li.active > a, .nav-pills > li.active > a:focus {
            background-color: #69899f;
            color: #d7e2e9;
        }</style>
    </head>

    <div class="row">
        <div class="col-md-12">
            <h1>Data Management</h1>
            <hr style="margin-top:0;"/>
        </div>
    </div>

    <!-- Column to list clickable indicators from db -->
    <div class="row">
        <div class="col-sm-3">
            <h3>Indicators</h3>
            <div class="panel panel-default">
                <div class="panel-body">

                    <!--button to reset and display all indicators-->
                    <a role="button"
                       href="{% url 'priv:dashboard1' %}"
                       class="btn btn-primary btn-med"
                       style="background-color:#69899f;color: #d7e2e9;">Reset Selection</a>

                    <!--add a space to better align left and right column data-->
                    <br/>
                    <table class="table">
                        {% for ind in indicators %}
                            <!-- Align indicator and edit button horizontally -->
                            <tr>
                                <td role="presentation" style="border:none"
                                    class="{% if selected_indicator and selected_indicator == ind %}active{% endif %}">
                                    <a href="{% url 'priv:dashboardselected' ind.id %}">
                                        {{ ind.name }}{% if ind.important %}&nbsp;&star;{% endif %}
                                    </a>
                                </td>
                                <td role="presentation" style="border:none">
                                    <a href="{% url 'priv:updateIndicator' ind.id %}">
                                        <i class="fa fa-edit"
                                           style="font-size:10px; color:#69899f;"
                                           title="Edit Indicator Name"></i>
                                    </a>
                                </td>
                                <td role="presentation" style="border:none">
                                    <a href="{% url 'priv:deleteIndicator' ind.id %}">
                                        <i class="fa fa-remove"
                                           style="font-size:15px; color:red;"
                                           title="Delete Indicator"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                    <br/>
                    <!-- Button to add a new indicator -->
                    <a role="button"
                       href="{% url 'priv:createIndicator' %}"
                       class="btn btn-primary btn-med"
                       style="background-color:#69899f;color: #d7e2e9;">Add Indicator</a>

                </div>
            </div>
        </div>

        <!-- Space between columns -->
        <div class="col-sm-1"></div>

        <!-- File list for specific indicator viewable by clickable indicators -->
        <div class="col-sm-8">
            <h3>{{ indicator_message }}</h3>
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead class="thead-light">
                        <tr>
                            <th scope="col">Year</th>
                            <th scope="col">Upload Date</th>
                            <th scope="col">User</th>
                            <th scope="col">File</th>
                            <th scope="col">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ds in datasets %}
                            <tr>
                                <td>{{ ds.year }}</td>
                                <td>{{ ds.source_document.uploaded_at }}</td>
                                <td>{{ ds.source_document.user }}</td>
                                <td>{{ ds.source_document.file }}</td>
                                <td><a href="{% url 'priv:deleteDataset' ds.id %}">
                                    <i class="fa fa-remove" style="font-size:15px; color:red;"
                                       title="Delete Dataset"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <a role="button"
                       href="{% url 'priv:uploadData' %}"
                       class="btn btn-primary btn-med"
                       style="background-color:#69899f;color: #d7e2e9;">Add Data</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hda_privileged/templates/hda_privileged/upload_metric.html
{% extends 'hda_privileged/base.html' %}

{% block title %}Upload Health Data{% endblock %}

{% block content %}

    <div class="jumbotron">
        <h2>Upload your Metric data here</h2>

        {% comment %}
      Show any messages added to the context
      by using Bootstrap alert components
      {% endcomment %}
        <div class='form-group'>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        {% if 'error' not in message.tags %}
                            <div
                                    class="alert alert-{{ message.level_tag }}"
                                    role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </ul>
                <ul class="messages">
                    <div class="label-warning">The following counties/states combinations are invalid:</div>

                        <table class="table table-responsive table-hover table-bordered">
                            {% for county,state in invalid_counties_and_states.items  %}

                                    <tr>
                                    <td> {{ county}}</td><td>{{ state }}</td></tr>

                            {% endfor %}
                        </table>

                </ul>
            {% endif %}
        </div>


        <form
                class="form-horizontal"
                method="POST"
                enctype="multipart/form-data"
                action="{% url 'priv:uploadData' %}">
            {% csrf_token %}

            {% for field in form.visible_fields %}
                {% comment %}
          An unordered list of validation messages
          {% endcomment %}
                {{ field.errors }}

                <div {% if field.errors %} class="form-group has-error" {% else %} class="form-group" {% endif %}>

                    {% comment %} Label associated to the input w/ id_for_label {% endcomment %}
                    <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>

                    {% comment %} The actual field/input element {% endcomment %}
                    <div class="col-sm-10">
                        {% if field == form.column_format %}
                            {% for radio in field %}
                                <div class="radio">
                                    {{ radio }}
                                </div>
                            {% endfor %}
                        {% else %}
                            {{ field }}
                        {% endif %}

                        {% comment %}
            Not using aria-describedby (but should be!) to link the field to its help text - 
            not sure how to inject that attribute into the django field output above
            {% endcomment %}
                        {% if field.help_text %}
                            <span class="help-block">{{ field.help_text | safe }}</span>
                        {% endif %}
                    </div>

                </div>
            {% endfor %}

        <button type="submit" class="btn btn-primary" onclick="TimeoutNow();" >Upload</button>
        <input class='btn btn-primary' onclick="window.history.back()" type="button" value='Cancel'/>
          <form>
              <!-- <input type="button" value="Upload" class="btn-primary" onclick="TimeoutNow();" /> -->

            </form>


        </form>
    </div>

{% endblock %}

{% block javascript %}
{% endblock %}

hda_privileged/templates/hda_privileged/usr_mgmt.html
{% extends 'hda_privileged/base.html' %}

{% block content %}

    {% comment %}User management template allows an administrator to view user accounts and click to create a new user,
deactivate an account, or change a user's password. Developed by Kim Hawkins{% endcomment %}

    {% comment %} Wrap the form in a panel for appearance {% endcomment %}
    <div class='panel panel-primary'>

        <div class="panel-heading" style="background-color:#69899f;color: #d7e2e9;">
            <h3 class="panel-title">User Management</h3>
        </div>

        <div class="panel-body">
            <h4 style="color:#69899f;">Current Users</h4>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    {% comment %}admin should not be able to reset superuser password{% endcomment %}
                    {% if not user.is_superuser and user.is_active %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>
                                {% comment %}pass user id in urlparams{% endcomment %}
                                <a href="{% url 'priv:pswd_reset' user.id %}"><i class="fa fa-key" aria-hidden="true"
                                                                                 style="color: #69899f;"> Reset
                                    Password</i></a></td>
                            <td>
                                <a href={% url 'priv:deactivate' user.id %}><i class="fa fa-remove"
                                                                               style="color: #69899f; "> Deactivate
                                    User </i> </a>
                            </td>

                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <a role="button"
               href="{% url 'priv:create_user' %}"
               class="btn btn-primary btn-med"
               style="background-color:#69899f;color: #d7e2e9;">Add User</a>
        </div>
{% endblock %}